apiVersion: v1
kind: Service
metadata:
  name: social-links-profile-main
  namespace: default
spec:
  selector:
    app: social-links-profile-main-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
